### ISSUE TITLE
cannot run on-demand backup for FileMaker Server (container)

### ISSUE THREAD

**Issue by kietnt072** [fmgarage/ft-fms-docker#11]
Hi, 

Thank you very much for your contribution to FMS Docker. 

It might be an issue -> I tried to run it on 2 devices: a Mac and a Linux, every thing work well except running a on demand backup. 

Please see the attached picture.

Thanks

<img width="1440" alt="Screen Shot 2021-10-31 at 5 31 01 PM" src="https://user-images.githubusercontent.com/42569231/139578716-46793e0c-9eea-4f00-9a70-ec2c279106b8.png">

**Comment by sk-gara** [comment]
Hello,
I can't see the issue on your screenshot, can you describe what goes wrong? I just tested the backup and it seems to work just fine.

**Comment by kietnt072** [comment]
Hi sk-gara,
Sorry for my late reply, I've removed all the containers on my Mac and run the scripts again. Now, I can run on-demand backup for it.

Thank you very much
