### ISSUE TITLE
build not successful failed to create bus connection

### ISSUE THREAD

**Issue by ayescas** [fmgarage/ft-fms-docker#12]
Hello,
trying to install and I'm getting the following error:

timezone from host: America/Los_Angeles 

Failed to create bus connection: No such file or directory
error while setting timezone
build not successful
stopping & removing build container ...
fmsinstall
fmsinstall

**Comment by sk-gara** [comment]
Hello,
is it possible the error message says it can't create the `d-bus` connection?
Which OS are you using?

**Comment by ayescas** [comment]
Thank you, MacOs 10.15.7

**Comment by sk-gara** [comment]
Alright, that rules out problems based on Big Sur and up. And the FMS version? Most recent on Ubuntu?
It looks like timedatectl can not be executed correctly inside the container. For that, elevated permissions and the /run directory are necessary, which should be provided by the install script that starts the container. Are there any other errors prior to this one by any chance?

**Comment by sk-gara** [comment]
Okay, i get the same error. Something has changed with Ubuntu I suspect. I'm gonna look into it.

**Comment by ayescas** [comment]
Thank you.  It was working fine and the recent Docker update broke it.

MacOs: 10.15.7
Docker: Version 4.3.1 engine 20.10.11

Tried to reinstall with no luck and tried the following FMS:
filemaker-server_19.4.2.204_amd64.deb
filemaker-server_19.3.2.203_amd64.deb
filemaker_server-19.2.1-23.x86_64.rpm

Here is more info on the error:
Current default time zone: 'Etc/UTC'
Local time is now:      Mon Dec 20 01:47:54 UTC 2021.
Universal Time is now:  Mon Dec 20 01:47:54 UTC 2021.
Run 'dpkg-reconfigure tzdata' if you wish to change it.

Failed to create bus connection: No such file or directory
error while setting timezone
build not successful
stopping & removing build container ...
fmsinstall
fmsinstall


-Alex



From: S ***@***.***>
Date: Monday, December 20, 2021 at 1:45 AM
To: fmgarage/ft-fms-docker ***@***.***>
Cc: Alejandro Yescas ***@***.***>, Author ***@***.***>
Subject: Re: [fmgarage/ft-fms-docker] build not successful failed to create bus connection (Issue #12)

Okay, i get the same error. Something has changed with Ubuntu I suspect. I'm gonna look into it.

**Comment by sk-gara** [comment]
It seems to me that running a Docker container with a systemd environment inside is not possible any more, at least in the way we did that. I suspect one the recent versions of Docker (Desktop). The root problem seems to be that the cgroup volume that is mounted into the container and that is needed by systemd does not work the way it did anymore. Systemd can't be started and so all services started by systemd itself. I'm not sure at this point if this can be fixed.

See also:
https://github.com/systemd/systemd/issues/19245
https://serverfault.com/questions/1053187/systemd-fails-to-run-in-a-docker-container-when-using-cgroupv2-cgroupns-priva/1054414#1054414
https://github.com/moby/moby/issues/42275

**Comment by sk-gara** [comment]
I tested with Windows WSL and Linux (Debian 10) and these still work. I guess because they can provide `/sys/fs/cgroup` from the host and are still on cgroup v1.

**Comment by sk-gara** [comment]
closed with https://github.com/fmgarage/ft-fms-docker/commit/bfec8bb04ea28121c1006b07569043ae18ab3b76
