### ISSUE TITLE
Install Script somehow messes up localhost networking

### ISSUE THREAD

**Issue by marcel-more** [fmgarage/ft-fms-docker#3]
After installing the ft-fms-docker on a Mac (macOS 10.15.7 on Intel) it worked once.
But after every new start of the FMS container the startup process will stop with some sort of networking error:

> Cannot start Docker Compose application. Reason: Error invoking remote method 'compose-action': Error: Command failed: docker-compose --file "docker-compose.yml" --project-name "fms-linux" --project-directory "/Users/xxx/Documents/FMS-Linux" up -d Starting fms-fms19 ... Creating reverse ... Starting fms-fms19 ... error ERROR: for fms-fms19 Cannot start service fms: Ports are not available: listen tcp 0.0.0.0:5003: bind: address already in use Creating reverse ... error ERROR: for reverse Cannot start service reverse: Ports are not available: listen tcp 0.0.0.0:5003: bind: address already in use ERROR: for fms Cannot start service fms: Ports are not available: listen tcp 0.0.0.0:5003: bind: address already in use ERROR: for reverse Cannot start service reverse: Ports are not available: listen tcp 0.0.0.0:5003: bind: address already in use Encountered errors while bringing up the project.

No other services are running on the machine on Port 5003 as far as I know.

I tried to delete the container and do a fresh install with the help of the ft-fms-docker install.sh script.
It worked a few times. But then same error happens again and again.

Sometimes nginx service is installed automatically inside the FMS container for no suitable reason. Why is this happening?

An the other hand:
My MAMP service stopped working on localhost. (This is not permanently running, only on demand).

There seems to be some conflict with the services on localhost.
Did not find any solution to it, yet.

Any help would be appreciated. Thanks!

**Comment by sk-gara** [comment]
The service 'reverse' should not exist in the compose file anymore, I think I messed that up with a merge from our develop repository. I will fix that.
You need to get rid of the 'reverse' container (stop, delete) and after the fix, download/clone the latest version.

**Comment by sk-gara** [comment]
Okay, it was only the 'reverse' block in the `docker-compose.yml`, no more old code that sneaked in.

Thanks for bringing it up!
