### ISSUE TITLE
Error: Cannot start service fms: Ports are not available

### ISSUE THREAD

**Issue by marcel-more** [fmgarage/ft-fms-docker#4]
Fresh install is failing due to "address already in use" (please refer to error message below).
But there are no other services running at this time.

Does this mean inside the docker container, or on the host system?
How to detect and solve the conflict?

> fmsinstall
> 
> Done. Now starting your server ....
> Creating fms-FMS19 ... error
> 
> ERROR: for fms-FMS19  Cannot start service fms: Ports are not available: listen tcp 0.0.0.0:5003: bind: address already in use
> 
> ERROR: for fms  Cannot start service fms: Ports are not available: listen tcp 0.0.0.0:5003: bind: address already in use
> ERROR: Encountered errors while bringing up the project.

**Comment by sk-gara** [comment]
That is an indicator that port 5003 is already taken by another application, most likely the FileMaker Pro client. You can check with the output of `sudo lsof -i -P | grep 5003` .

**Comment by marcel-more** [comment]
> That is an indicator that port 5003 is already taken by another application, most likely the FileMaker Pro client. You can check with the output of `lsof -i -P | grep 5003` .

OK, I see.... yes it's the FileMaker Client.
So if I want to start the docker container with FMS I have to close my local FileMaker client first!
Not that intuitive, but makes sense from the perspective of the network ports.
Thanks for the hint! Made my day :-)

**Comment by sk-gara** [comment]
Good to hear!
That behaviour of FileMaker Pro, to take that port exclusively, even with sharing turned off, is relatively new from what I heard. So yes, no other way around here I'm afraid.
