### ISSUE TITLE
only UTC Timezone by default, how to extend for other Timezones

### ISSUE THREAD

**Issue by marcel-more** [fmgarage/ft-fms-docker#6]
This would be a nice addition in the Ubuntu install script:

```
apt-get install -y tzdata
timedatectl set-timezone Europe/Berlin
```

The first Line installs the whole List for available Timezones on Ubuntu. By default there is only UTC preinstalled.

The second line sets the Timezone to "Europe/Berlin" to set the Host to the same time which the Client has (if you are working in Germany).

The problem without this setting could be, that you make use of the function "Get(CurrentHostTimestamp)" or "Hole ( HostZeitstempel )" in your solution and get wrong timestamps. This could then lead to further problems if you make use of synchronization processes within your solution.

**Comment by sk-gara** [comment]
You are right, the correct timezone should be set on the server machine. I'm thinking, would it be better to manually set this as a config or to automatically determine from the host during install?
